sudo: false

language: node_js

node_js:
  - node

install:
  - npm ci
cache:
  directories:
    - node_modules
    
script:
  - npm run eslint
  - npm run test:coveralls

notifications:
  email:false